### ISSUE TITLE
Working with IOS9 and Ionic2?

### ISSUE THREAD

**Issue by rachelxi** [recaisinekli/rtspPlayer#1]
working on the ios9 and ionic 2 framework to display rtsp stream but not showing anything

**Comment by recaisinekli** [comment]
As far as I know ionic framework doesn't support cordova plugins out of the box. You should use an Angular.js wrapper. Check out http://ngcordova.com

Here is a tutorial about using cordova plugins in ionic 2 : http://www.joshmorony.com/using-cordova-plugins-in-ionic-2-with-ionic-native/

**Comment by rachelxi** [comment]
well, I probably didn't specify what I was doing. I was using cordova plugin streaming-media to display the rtsp streams coming from IP camera and it works fine on the android 4.0+; however, the plugin is using MPMoiviePlayerController on IOS, which does not support rtsp.

So that's why I'm detecting the platform with ionic-angular and just tested your plugin on my Iphone with IOS 9.3; I am still using the plugin with ionic2 and cordova instead of natively. In this case, it's still not working properly. 

And thanks for your reply!
