### ISSUE TITLE
This rtspPlayer is a restricted version? Can only use 2 minutes? How to release?

### ISSUE THREAD

**Issue by Harris-Aaron** [recaisinekli/rtspPlayer#2]
It's the restricted version error, but how to git full version?

```
11:52:42:player.c(2373) --> player_notify: 105 
11:52:42:player.c(2462) --> player_notify: CallVoidMethod 105 
2016-10-09 11:52:42.011240 live[335:104104] Notify: 105
11:52:42:player.c(2488) --> player_notify: CallVoidMethod return 105 
11:52:42:recorder_provider_thread.c(604) --> =rec PP_RECORD_STAT_PKT_COUNT *pvalue(20)
11:52:42:ffmpeg_content_provider.c(255) --> timeout_interrupt_callback guard time: 120000000, first:87143942219, diff:146629912
11:52:42:ffmpeg_content_provider.c(255) --> timeout_interrupt_callback guard time: 120000000, first:87143942219, diff:146642445
11:52:42:ffmpeg_content_provider.c(1709) --> MEDIA(src) ffmpeg_cp_get_data DATA_RECEIVE_TIME_OUT disc s(87290560681) n(0) averror(dfb9b0bb)
```

**Comment by recaisinekli** [comment]
This player is based on VXG Video Player SDK. You need to buy full version of this iOS SDK from [VXG](https://www.videoexpertsgroup.com/vxg-video-sdk/) to watch more than 2 minutes. After you buy the SDK change the files under "src->ios->lib".

**Comment by digu143** [comment]
how to buy can u tell me and what is the cost? i am getting the same problem. please tell me as soon as possible

**Comment by fendis0709** [comment]
Yes, I have same problem too. How to get full version?

**Comment by recaisinekli** [comment]
@digu143 @fendiseptiawan0709 As mentioned before, this player is based on VXG Video Player SDK. You need to buy full version of this iOS SDK from [VXG](https://www.videoexpertsgroup.com/vxg-video-sdk/) to watch more than 2 minutes. After you buy the SDK change the files under "src->ios->lib".
