### ISSUE TITLE
How add rtspPlayer plugin to my project

### ISSUE THREAD

**Issue by soniatrs** [recaisinekli/rtspPlayer#8]
Hi, how can I add your plugin in my cordova project? I use phonegap build.
Tanks in advance

**Comment by recaisinekli** [comment]
Hi, I don't use phonegap. If you are not able to add the plugin using the command below I'm afraid you need to install it [manually](http://docs.phonegap.com/phonegap-build/configuring/plugins/#importing-config).

`phonegap plugin add https://github.com/recaisinekli/rtspPlayer.git`

**Comment by soniatrs** [comment]
thanks, I'll try this way.
